news/urls.py
from django.urls import path

from news.views import NewsList, NewsDetail

app_name = "news"

urlpatterns = [
    path("", NewsList.as_view()),
    path("<int:pk>/", NewsDetail.as_view()),
]

recipesProject/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from rest_framework import permissions
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import routers
from recipes.views import *
from users.views import UsersViewSet
router = routers.DefaultRouter()

router.register(r'recipes',RecipeViewSet)
router.register(r'ingredientamounts',IngredientAmountViewSet)
router.register(r'ingredients',IngredientViewSet)
router.register(r'users',UsersViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Recipes project API",
        default_version="v1",
        description="Recipes project APO",
    ),
    public=True,
    permission_classes=[permissions.IsAdminUser],
)

urlpatterns = [

     path('api/v1/',include(router.urls)),



    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("auth/", include(("users.urls", "users"), namespace="users")),
    path("recipes/", include(("recipes.urls", "recipes"), namespace="recipes")),
    path("news/", include(("news.urls", "news"), namespace="news")),
   
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from users.views import UserList, UserDetail, CurrentUser, UsersListView, UserDetailView, SignupView, ProfileView

app_name = 'users'

urlpatterns = [
    # path("users/", UserList.as_view()),
    # path("users/<int:pk>/", UserDetail.as_view()),
    # path("users/current/", CurrentUser.as_view()),
    path('login/',
         LoginView.as_view(
             template_name='users/login.html'),
         name='login'),
    path('users/',
         UsersListView.as_view(),
         name='users_list'),
    path('users/<int:id>/',
         UserDetailView.as_view(),
         name='user_detail'),

    path('signup/',
         SignupView.as_view(),
         name='signup'),
    path('profile/',
         ProfileView.as_view(),
         name='profile'),
]

templates/includes/form.html
<div class='base-form col-12 col-sm-10 col-md-9 col-lg-9 col-xl-6'>
    {% load static %}
    <div class='base-form__errors'>
        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <span class="text-danger">{{ error|escape }}</span>
            {% endfor %}
        {% endif %}
    </div>

    <form method='POST' class='base-form__form' {% if form.is_multipart %} enctype="multipart/form-data" {% endif %}>
        {% csrf_token %}
        {% for field in form %}
            <div class='base-form__form-row'>
                <label for='{{ field.id_for_label }}' class="form-label">
                    {{ field.label }}
                    {% if field.field.required %}
                        <span class='base-form__star'>*</span>
                    {% endif %}
                </label>
                <div class="base-form__field-errors">
                    {% for error in field.errors %}
                        <span class="text-danger">{{ error|escape }}</span>
                    {% endfor %}
                </div>
                {{ field }}
                {% if field.help_text %}
                    <small id='{{ field.id_for_label }}-help'>
                        {{ field.help_text|safe }}
                    </small>
                {% endif %}
            </div>
        {% endfor %}

        <div class='form-buttons-container'>
            <button name='edit' type='submit' class='btn btn-primary d-block mt-3'>{{ submit_text }}</button>
            {% if edit %}
                <button type='button' class='submit-btn delete-btn btn'>Удалить</button>
            {% endif %}
        </div>
        {% if show_register_link %}
            <span class='base-form__link'>
                Первый раз на сайте?  <a href='{% url "users:signup" %}'>Создать аккаунт!</a>
            </span>
        {% endif %}
        {% if show_already_have_account %}
            <span class='base-form__link'>
                Уже есть аккаунт? <a href='{% url "users:login" %}'>Войти</a>
            </span>
        {% endif %}
    </form>
</div>